### ISSUE TITLE
Not compatible with netstandard2.0

### ISSUE THREAD

**Issue by amjadkhan** [Xabaril/AspNetCore.Hashids#7]
Tried to add package to a .Net Standard 2.0 project and generated an Error code NU1202 "Package AspNetCore.Hashids 1.1.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package AspNetCore.Hashids 1.1.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)"

**Comment by lurumad** [comment]
Hi @amjadkhan 

This package was created with the intention of being used in ASP.NET Core applications, for this reason target to netcoreapp3.1. If you want to hash your ids in a netstandard library you can use  https://github.com/ullmark/hashids.net

Regards!
