### ISSUE TITLE
Bypassing the hashing.

### ISSUE THREAD

**Issue by Abdulrhman5** [Xabaril/AspNetCore.Hashids#8]
https://github.com/Xabaril/AspNetCore.Hashids/blob/5360e4646c3cbd7fda8822b6a572ccfbaabd4205/src/AspNetCore.Hashids/Json/HashidsJsonConverter.cs#L27

if you supply the id as an integer this converter will accept it instead of throwing an error.

**Comment by unaizorrilla** [comment]
Hi @Abdulrhman5 

It' is true... @lurumad are you able to do that?

**Comment by unaizorrilla** [comment]
Hi @Abdulrhman5 

PR is on the way!

https://github.com/Xabaril/AspNetCore.Hashids/pull/9

**Comment by unaizorrilla** [comment]
Hi @Abdulrhman5 

A new preview https://www.nuget.org/packages/AspNetCore.Hashids/1.2.0-preview10 is on NuGet. Can you check it and let me know if all is working as expected?

Remember use the new opt-in to configure if clean ids are allowed or not

**Comment by Abdulrhman5** [comment]
Perfect, Thank you so much :)
